# Generated by Django 6.0.2 on 2026-04-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_telegram", "0002_alter_telegramchat_chat_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grouprepo_groups",
                        to="django_telegram.telegramchat",
                    ),
                ),
                (
                    "repo_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grouprepo_repos",
                        to="django_telegram.telegramchat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField()),
                ("message_id", models.BigIntegerField()),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_notes.grouprepo",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="grouprepo",
            constraint=models.UniqueConstraint(
                fields=("group_chat",), name="unique_repo_per_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="grouprepo",
            constraint=models.UniqueConstraint(
                fields=("repo_chat",), name="unique_group_per_repo"
            ),
        ),
        migrations.AddConstraint(
            model_name="repoitem",
            constraint=models.UniqueConstraint(
                fields=("repo", "key"), name="unique_key_per_repo"
            ),
        ),
    ]
