# Generated by Django 6.0.2 on 2026-04-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading_portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="readingportal",
            name="closes_at",
        ),
        migrations.RemoveField(
            model_name="readingportal",
            name="opens_at",
        ),
    ]
