# Generated by Django 6.0.2 on 2026-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_portal", "0002_remove_readingportal_closes_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingportal",
            name="portal_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
