# Generated by Django 6.0.2 on 2026-05-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_portal", "0003_alter_readingportal_portal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingportal",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="readingportal",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
