# Generated by Django 6.0.2 on 2026-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_telegram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramchat",
            name="chat_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("private", "private"),
                    ("group", "group"),
                    ("supergroup", "supergroup"),
                    ("channel", "channel"),
                ],
                max_length=20,
            ),
        ),
    ]
